{% set name = "idds-common" %}
{% set name_pypi = "idds_common" %}
{% set version = "2.6.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/8b/f3/7e1973b30d468e3d782523a4ddb50e8b063ede0fa13e079a18c20e160bf4/idds_common-2.6.11-py3-none-any.whl
  sha256: fab90ab69b7c911c6c0dfe9a36af8cd557193fe94dccbbbab443d3d55ba40df7

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - cryptography
    - pyjwt
    - packaging
    - requests
    - dogpile.cache
    - deepdiff

test:
  requires:
    - python {{ python_min }}
  imports:
    - idds
    - idds.common

about:
  home: https://pypi.org/project/idds-common/
  summary: intelligent Distributed Dispatch and Scheduling (iDDS) Package
  dev_url: https://github.com/HSF/iDDS
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - wguanicedew
    - yesw2000
