{% set name = "idds-common" %}
{% set name_pypi = "idds_common" %}
{% set version = "2.6.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name_pypi }}/{{ name_pypi }}-{{ version }}.tar.gz
  sha256: 904e47a7cd4e6ebe5713f49429382efd154350a2c38ad7aff423a65569ddd92d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - cryptography
    - pyjwt
    - packaging
    - requests
    - dogpile.cache
    - deepdiff

test:
  requires:
    - python {{ python_min }}
  imports:
    - idds
    - idds.common

about:
  home: https://pypi.org/project/idds-common/
  summary: intelligent Distributed Dispatch and Scheduling (iDDS) Package
  dev_url: https://github.com/HSF/iDDS
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - wguanicedew
    - yesw2000
